spring.application.name=generator
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.api-key=test-key
server.port=9021



# Suppress WARN logs from FileSystemFontProvider
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

spring.docker.compose.lifecycle-management=start_only

# Gemini API Configuration
gemini.api.key=AIzaSyCdHepWCWmmX_pQY8FEeRdLN5_FtwWSutM

# If using manual PG settings instead of docker-compose defaults:
spring.datasource.url=jdbc:postgresql://localhost:5432/insightsDb
spring.datasource.username=deladm
spring.datasource.password=D3lphi95

# Logs the actual SQL and connection health checks
logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework.jdbc.datasource=INFO

# Spring AI PGVector settings
spring.ai.vectorstore.pgvector.initialize-schema=true