spring.application.name=generator
##spring.ai.openai.api-key=${OPENAI_API_KEY}
##spring.ai.openai.chat.options.model=gpt-4o
#spring.ai.openai.api-key=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
server.port=9021


# Gemini API Configuration

# Explicitly set for both modules to avoid Vertex AI fallback
#spring.ai.google.genai.api-key=AIzaSyCdHepWCWmmX_pQY8FEeRdLN5_FtwWSutM
#spring.ai.google.genai.chat.api-key=AIzaSyCdHepWCWmmX_pQY8FEeRdLN5_FtwWSutM
#spring.ai.google.genai.embedding.api-key=AIzaSyCdHepWCWmmX_pQY8FEeRdLN5_FtwWSutM
spring.ai.google.genai.api-key=AIzaSyCz21LbpBixA9iPL1rYEeMgYnMSBdXAhYo
spring.ai.google.genai.chat.api-key=AIzaSyCz21LbpBixA9iPL1rYEeMgYnMSBdXAhYo
spring.ai.google.genai.embedding.api-key=AIzaSyCz21LbpBixA9iPL1rYEeMgYnMSBdXAhYo

# Optional: Specify the model (e.g., gemini-1.5-pro or gemini-1.5-flash)
spring.ai.google.genai.embedding.options.model=text-embedding-001
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview
spring.ai.google.genai.project-id=unused
# Request a smaller vector size from Gemini

spring.ai.google.genai.embedding.options.output-dimensionality=768


# Force the Vector Store to only create columns for 768 dimensions
spring.ai.vectorstore.pgvector.dimensions=768

# Use HNSW (now safe since 768 < 2000)
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.initialize-schema=true


spring.jpa.hibernate.ddl-auto=update

# Suppress WARN logs from FileSystemFontProvider
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

spring.docker.compose.lifecycle-management=start_only

# Gemini API Configuration
gemini.api.key=AIzaSyCdHepWCWmmX_pQY8FEeRdLN5_FtwWSutM

# If using manual PG settings instead of docker-compose defaults:
spring.datasource.url=jdbc:postgresql://localhost:5432/insightsDb
spring.datasource.username=deladm
spring.datasource.password=D3lphi95

# Logs the actual SQL and connection health checks
logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework.jdbc.datasource=INFO

